server:
  port: 1112

# Spring
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/video_download?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
  resources:
    static-locations: classpath:static/,file:static/
  # 模板引擎
  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.videodownload.domain

#showSql
logging:
  level:
    com:
      example:
        mapper : debug

file-dir: D:/test/
file-dir1: upload/
file-dir2: upload2/
server-url: http://192.168.1.20:1112
